In [63]:
# Import libraries
import os
import boto3
import pandas as pd
import sys
from path import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import psycopg2
import sqlalchemy
import matplotlib as plt
%matplotlib inline

In [64]:
# Get the S3 keys from config file
from config import aws_id, aws_secret, postgres_key

In [65]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import psycopg2
import pandas.io.sql as sqlio

# Upload fec_df to sql database
conn = psycopg2.connect(f"host=projectdatabase.c1ibogbs35nd.us-east-2.rds.amazonaws.com dbname=election_results user=postgres password={postgres_key}")
cur = conn.cursor()
cur.execute("SELECT state_district, name, party, incumbent_challenger_open, receipts, from_individuals, from_committees, from_candidate, disbursements, cash_on_hand, debts from fec_2018")
#with open("Resources/fec.csv", "r") as f:
 #   next(f) # Skip the header row.
  #  cur.copy_from(f, "fec", sep=",")
#conn.commit()

rows = cur.fetchall()
rows

In [67]:
# Connect to final table in SQL
sql = "SELECT state_district, election, name, party, incumbent_challenger_open, receipts, from_individuals, from_committees, from_candidate, disbursements, cash_on_hand, debts, district, election_year, total_pop, male_pop_percent, female_pop_percent, under_five_percent, five_to_nine_percent,ten_to_fourteen_percent,fifteen_nineteen_percent,twenty_to_twentyfour_percent,twentyfive_to_thirtyfour_percent ,thirtyfive_to_fortyfour_percent ,fortyfive_to_fiftyfour_percent ,fiftyfive_to_fiftynine_percent ,sixty_to_sixtyfour_percent ,sixtyfive_to_seventyfour_percent ,seventyfive_to_eightyfour_percent ,over_eightyfive_percent ,median_age, eighteen_and_over_percent ,twentyone_and_over_percent ,sixtytwo_and_over_percent ,sixtyfive_and_over_percent ,eighteen_and_over_male_percent ,eighteen_and_over_female_percent ,sixtyfive_and_over_male_percent ,sixtyfive_and_over_female_percent ,white_pop_percent ,black_pop_percent ,american_indian_alaska_native_pop_percent ,asian_pop_percent ,native_hawaiian_pacific_islander_pop_percent ,other_race_pop_percent ,hispanic_pop_percent , total_housing_units, last_name, first_name, prefix, first_last_name, district_from_length, candidate_name, spent, won, lost, incumbent, challenger, open_seat, election_year_from_length, party_from_length, year, Last_name, firstlast_name from final_table_1"
final_summary = sqlio.read_sql_query(sql, conn)
final_summary

,state_district,election,name,party,incumbent_challenger_open,receipts,from_individuals,from_committees,from_candidate,disbursements,...,won,lost,incumbent,challenger,open_seat,election_year_from_length,party_from_length,year,last_name,firstlast_name
0,IL06,2014.0,ROSKAM PETER,Republican Party,Incumbent,2643875.43,1137871.17,1443315.73,0.00,2543254.32,...,1,0,1,0,0,2014,Republican,2007.0,Roskam,Peter Roskam
1,TX05,2014.0,HENSARLING JEB HON.,Republican Party,Incumbent,2673006.24,1384157.24,1234898.00,0.00,3084464.90,...,1,0,1,0,0,2014,Republican,2003.0,Hensarling,Jeb Hensarling
2,LA01,2014.0,SCALISE STEVE MR.,Republican Party,Incumbent,1425973.57,567158.50,854339.38,0.00,1168222.75,...,1,0,1,0,0,2014,Republican,2008.0,Scalise,Steve Scalise
3,NY14,2014.0,CROWLEY JOSEPH,Democratic Party,Incumbent,2522320.53,623251.17,1286586.77,0.00,1946781.49,...,1,0,1,0,0,2014,Democrat,1999.0,Crowley,Joseph Crowley
4,TX08,2014.0,BRADY KEVIN,Republican Party,Incumbent,2018388.20,439001.78,1223160.02,0.00,1010201.52,...,1,0,1,0,0,2014,Republican,1997.0,Brady,Kevin Brady
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4872,CA34,2018.0,CARMONA ARTURO,Democratic Party,Open,155331.16,142631.16,9700.00,3000.00,244941.43,...,0,1,0,0,0,0,0,0.0,Carmona,0
4873,TX21,2018.0,POTEET ALONZO MARCUS MR. III,Republican Party,Open,27518.18,6795.67,0.00,20722.51,30835.17,...,0,1,0,0,0,0,0,0.0,Poteet,0
4874,WA08,2018.0,MARTS TOLA,Democratic Party,Open,74353.87,73493.85,0.00,860.02,74353.87,...,0,1,0,0,0,0,0,0.0,Marts,0
4875,OH02,2018.0,EVERHARD JANET,Democratic Party,Challenger,57777.75,29205.37,500.00,28072.38,54737.28,...,0,1,0,0,0,0,0,0.0,Everhard,0
4876,OK06,2014.0,RAINWATER MARILYN,Democratic Party,Challenger,1000.00,1000.00,0.00,0.00,1000.00,...,0,1,0,0,0,0,0,0.0,Rainwater,0

In [68]:
# Look at spent column of final table
final_summary['spent']

0       $4,079,869
1       $3,408,251
2       $2,735,431
3       $2,668,960
4       $2,184,911
           ...
4872              0
4873              0
4874              0
4875              0
4876              0
Name: spent, Length: 4877, dtype: object

In [69]:
# Take away $ and , from spent column
# Change the spring spent column to a number
final_summary['spent'] = final_summary['spent'].str.replace(',', '')
final_summary['spent'] = final_summary['spent'].str.replace('$', '')
final_summary['spent'] = final_summary['spent'].astype(int)
final_summary['spent']

0       4079869
1       3408251
2       2735431
3       2668960
4       2184911
         ...
4872          0
4873          0
4874          0
4875          0
4876          0
Name: spent, Length: 4877, dtype: int32

In [70]:
final_summary.head()

,state_district,election,name,party,incumbent_challenger_open,receipts,from_individuals,from_committees,from_candidate,disbursements,...,won,lost,incumbent,challenger,open_seat,election_year_from_length,party_from_length,year,last_name,firstlast_name
0,IL06,2014.0,ROSKAM PETER,Republican Party,Incumbent,2643875.43,1137871.17,1443315.73,0.0,2543254.32,...,1,0,1,0,0,2014,Republican,2007.0,Roskam,Peter Roskam
1,TX05,2014.0,HENSARLING JEB HON.,Republican Party,Incumbent,2673006.24,1384157.24,1234898.00,0.0,3084464.90,...,1,0,1,0,0,2014,Republican,2003.0,Hensarling,Jeb Hensarling
2,LA01,2014.0,SCALISE STEVE MR.,Republican Party,Incumbent,1425973.57,567158.50,854339.38,0.0,1168222.75,...,1,0,1,0,0,2014,Republican,2008.0,Scalise,Steve Scalise
3,NY14,2014.0,CROWLEY JOSEPH,Democratic Party,Incumbent,2522320.53,623251.17,1286586.77,0.0,1946781.49,...,1,0,1,0,0,2014,Democrat,1999.0,Crowley,Joseph Crowley
4,TX08,2014.0,BRADY KEVIN,Republican Party,Incumbent,2018388.20,439001.78,1223160.02,0.0,1010201.52,...,1,0,1,0,0,2014,Republican,1997.0,Brady,Kevin Brady

In [71]:
final_summary.columns

Index(['state_district', 'election', 'name', 'party',
       'incumbent_challenger_open', 'receipts', 'from_individuals',
       'from_committees', 'from_candidate', 'disbursements', 'cash_on_hand',
       'debts', 'district', 'election_year', 'total_pop', 'male_pop_percent',
       'female_pop_percent', 'under_five_percent', 'five_to_nine_percent',
       'ten_to_fourteen_percent', 'fifteen_nineteen_percent',
       'twenty_to_twentyfour_percent', 'twentyfive_to_thirtyfour_percent',
       'thirtyfive_to_fortyfour_percent', 'fortyfive_to_fiftyfour_percent',
       'fiftyfive_to_fiftynine_percent', 'sixty_to_sixtyfour_percent',
       'sixtyfive_to_seventyfour_percent', 'seventyfive_to_eightyfour_percent',
       'over_eightyfive_percent', 'median_age', 'eighteen_and_over_percent',
       'twentyone_and_over_percent', 'sixtytwo_and_over_percent',
       'sixtyfive_and_over_percent', 'eighteen_and_over_male_percent',
       'eighteen_and_over_female_percent', 'sixtyfive_and_over_male_percent',
       'sixtyfive_and_over_female_percent', 'white_pop_percent',
       'black_pop_percent', 'american_indian_alaska_native_pop_percent',
       'asian_pop_percent', 'native_hawaiian_pacific_islander_pop_percent',
       'other_race_pop_percent', 'hispanic_pop_percent', 'total_housing_units',
       'last_name', 'first_name', 'prefix', 'first_last_name',
       'district_from_length', 'candidate_name', 'spent', 'won', 'lost',
       'incumbent', 'challenger', 'open_seat', 'election_year_from_length',
       'party_from_length', 'year', 'last_name', 'firstlast_name'],
      dtype='object')

In [72]:
# 'last_name', 'first_name', 'prefix', 'first_last_name', 'district_from_length', 'candidate_name', 'incumbent', 
# 'challenger', 'open_seat', 'election_year_from_length', 'party_from_length', 'Last_name', 'firstlast_name'

In [73]:
# Drop unnecessary columns for machine learning
final_summary_drop_columns = final_summary.drop(columns=['election_year','last_name', 'first_name', 'prefix', 'first_last_name', 'district_from_length', 'candidate_name', 'incumbent', 'challenger', 'open_seat', 'election_year_from_length', 'party_from_length','state_district','district'])
final_summary_drop_columns.head()

,election,name,party,incumbent_challenger_open,receipts,from_individuals,from_committees,from_candidate,disbursements,cash_on_hand,...,asian_pop_percent,native_hawaiian_pacific_islander_pop_percent,other_race_pop_percent,hispanic_pop_percent,total_housing_units,spent,won,lost,year,firstlast_name
0,2014.0,ROSKAM PETER,Republican Party,Incumbent,2643875.43,1137871.17,1443315.73,0.0,2543254.32,1143860.44,...,8.9,0.0,0.1,10.0,270685.0,4079869,1,0,2007.0,Peter Roskam
1,2014.0,HENSARLING JEB HON.,Republican Party,Incumbent,2673006.24,1384157.24,1234898.00,0.0,3084464.90,1472329.77,...,1.8,0.1,0.1,27.9,286382.0,3408251,1,0,2003.0,Jeb Hensarling
2,2014.0,SCALISE STEVE MR.,Republican Party,Incumbent,1425973.57,567158.50,854339.38,0.0,1168222.75,858641.66,...,2.0,0.0,0.2,8.8,330578.0,2735431,1,0,2008.0,Steve Scalise
3,2014.0,CROWLEY JOSEPH,Democratic Party,Incumbent,2522320.53,623251.17,1286586.77,0.0,1946781.49,1364191.18,...,16.0,0.0,0.4,49.8,262554.0,2668960,1,0,1999.0,Joseph Crowley
4,2014.0,BRADY KEVIN,Republican Party,Incumbent,2018388.20,439001.78,1223160.02,0.0,1010201.52,1325444.21,...,2.2,0.0,0.0,22.4,290582.0,2184911,1,0,1997.0,Kevin Brady

In [74]:
final_summary_drop_columns.columns

Index(['election', 'name', 'party', 'incumbent_challenger_open', 'receipts',
       'from_individuals', 'from_committees', 'from_candidate',
       'disbursements', 'cash_on_hand', 'debts', 'total_pop',
       'male_pop_percent', 'female_pop_percent', 'under_five_percent',
       'five_to_nine_percent', 'ten_to_fourteen_percent',
       'fifteen_nineteen_percent', 'twenty_to_twentyfour_percent',
       'twentyfive_to_thirtyfour_percent', 'thirtyfive_to_fortyfour_percent',
       'fortyfive_to_fiftyfour_percent', 'fiftyfive_to_fiftynine_percent',
       'sixty_to_sixtyfour_percent', 'sixtyfive_to_seventyfour_percent',
       'seventyfive_to_eightyfour_percent', 'over_eightyfive_percent',
       'median_age', 'eighteen_and_over_percent', 'twentyone_and_over_percent',
       'sixtytwo_and_over_percent', 'sixtyfive_and_over_percent',
       'eighteen_and_over_male_percent', 'eighteen_and_over_female_percent',
       'sixtyfive_and_over_male_percent', 'sixtyfive_and_over_female_percent',
       'white_pop_percent', 'black_pop_percent',
       'american_indian_alaska_native_pop_percent', 'asian_pop_percent',
       'native_hawaiian_pacific_islander_pop_percent',
       'other_race_pop_percent', 'hispanic_pop_percent', 'total_housing_units',
       'spent', 'won', 'lost', 'year', 'firstlast_name'],
      dtype='object')

In [75]:
# Drop first and last name column
final_summary_drop_columns = final_summary_drop_columns.drop(columns=['name', 'firstlast_name'])
final_summary_drop_columns.head()

,election,party,incumbent_challenger_open,receipts,from_individuals,from_committees,from_candidate,disbursements,cash_on_hand,debts,...,american_indian_alaska_native_pop_percent,asian_pop_percent,native_hawaiian_pacific_islander_pop_percent,other_race_pop_percent,hispanic_pop_percent,total_housing_units,spent,won,lost,year
0,2014.0,Republican Party,Incumbent,2643875.43,1137871.17,1443315.73,0.0,2543254.32,1143860.44,15607.71,...,0.0,8.9,0.0,0.1,10.0,270685.0,4079869,1,0,2007.0
1,2014.0,Republican Party,Incumbent,2673006.24,1384157.24,1234898.00,0.0,3084464.90,1472329.77,0.00,...,0.4,1.8,0.1,0.1,27.9,286382.0,3408251,1,0,2003.0
2,2014.0,Republican Party,Incumbent,1425973.57,567158.50,854339.38,0.0,1168222.75,858641.66,0.00,...,1.1,2.0,0.0,0.2,8.8,330578.0,2735431,1,0,2008.0
3,2014.0,Democratic Party,Incumbent,2522320.53,623251.17,1286586.77,0.0,1946781.49,1364191.18,0.00,...,0.0,16.0,0.0,0.4,49.8,262554.0,2668960,1,0,1999.0
4,2014.0,Republican Party,Incumbent,2018388.20,439001.78,1223160.02,0.0,1010201.52,1325444.21,0.00,...,0.1,2.2,0.0,0.0,22.4,290582.0,2184911,1,0,1997.0

In [76]:
# calculate the years in service
final_summary_drop_columns['years_in_service'] = final_summary_drop_columns['election'] - final_summary_drop_columns['year']
final_summary_drop_columns['years_in_service']

0          7.0
1         11.0
2          6.0
3         15.0
4         17.0
         ...
4872    2018.0
4873    2018.0
4874    2018.0
4875    2018.0
4876    2014.0
Name: years_in_service, Length: 4877, dtype: float64

In [77]:
# Turn new canddiates to 0
years_in_service = final_summary_drop_columns['years_in_service']
final_summary_drop_columns['years_in_service'] = years_in_service[years_in_service > 2000] = 0
final_summary_drop_columns.tail()

C:\Users\briordan\Anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,election,party,incumbent_challenger_open,receipts,from_individuals,from_committees,from_candidate,disbursements,cash_on_hand,debts,...,asian_pop_percent,native_hawaiian_pacific_islander_pop_percent,other_race_pop_percent,hispanic_pop_percent,total_housing_units,spent,won,lost,year,years_in_service
4872,2018.0,Democratic Party,Open,155331.16,142631.16,9700.0,3000.00,244941.43,1285.31,45864.36,...,19.0,0.2,0.2,63.6,275827.0,0,0,1,0.0,0.0
4873,2018.0,Republican Party,Open,27518.18,6795.67,0.0,20722.51,30835.17,-3316.99,15158.99,...,3.6,0.0,0.1,30.3,358577.0,0,0,1,0.0,0.0
4874,2018.0,Democratic Party,Open,74353.87,73493.85,0.0,860.02,74353.87,0.00,0.00,...,9.6,0.8,0.3,12.1,297606.0,0,0,1,0.0,0.0
4875,2018.0,Democratic Party,Challenger,57777.75,29205.37,500.0,28072.38,54737.28,3090.47,0.00,...,1.5,0.0,0.2,2.0,325777.0,0,0,1,0.0,0.0
4876,2014.0,Democratic Party,Challenger,1000.00,1000.00,0.0,0.00,1000.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,0,0,1,0.0,0.0

In [78]:
# Creating dummy data
data_with_dummies = pd.get_dummies(final_summary_drop_columns, columns=["party","incumbent_challenger_open"])
data_with_dummies.head()

,election,receipts,from_individuals,from_committees,from_candidate,disbursements,cash_on_hand,debts,total_pop,male_pop_percent,...,won,lost,year,years_in_service,party_Democratic Party,party_Other,party_Republican Party,incumbent_challenger_open_Challenger,incumbent_challenger_open_Incumbent,incumbent_challenger_open_Open
0,2014.0,2643875.43,1137871.17,1443315.73,0.0,2543254.32,1143860.44,15607.71,727718.0,49.2,...,1,0,2007.0,7.0,0,0,1,0,1,0
1,2014.0,2673006.24,1384157.24,1234898.00,0.0,3084464.90,1472329.77,0.00,726896.0,50.4,...,1,0,2003.0,11.0,0,0,1,0,1,0
2,2014.0,1425973.57,567158.50,854339.38,0.0,1168222.75,858641.66,0.00,781134.0,48.6,...,1,0,2008.0,6.0,0,0,1,0,1,0
3,2014.0,2522320.53,623251.17,1286586.77,0.0,1946781.49,1364191.18,0.00,727544.0,51.3,...,1,0,1999.0,15.0,1,0,0,0,1,0
4,2014.0,2018388.20,439001.78,1223160.02,0.0,1010201.52,1325444.21,0.00,761764.0,51.0,...,1,0,1997.0,17.0,0,0,1,0,1,0

In [ ]:
# Drop the state_district
data_with_dummies = data_with_dummies.drop(columns=['state_district'])
data_with_dummies.head()

In [79]:
# Drop the state_district
data_with_dummies = data_with_dummies.drop(columns=['lost'])
data_with_dummies.head()

,election,receipts,from_individuals,from_committees,from_candidate,disbursements,cash_on_hand,debts,total_pop,male_pop_percent,...,spent,won,year,years_in_service,party_Democratic Party,party_Other,party_Republican Party,incumbent_challenger_open_Challenger,incumbent_challenger_open_Incumbent,incumbent_challenger_open_Open
0,2014.0,2643875.43,1137871.17,1443315.73,0.0,2543254.32,1143860.44,15607.71,727718.0,49.2,...,4079869,1,2007.0,7.0,0,0,1,0,1,0
1,2014.0,2673006.24,1384157.24,1234898.00,0.0,3084464.90,1472329.77,0.00,726896.0,50.4,...,3408251,1,2003.0,11.0,0,0,1,0,1,0
2,2014.0,1425973.57,567158.50,854339.38,0.0,1168222.75,858641.66,0.00,781134.0,48.6,...,2735431,1,2008.0,6.0,0,0,1,0,1,0
3,2014.0,2522320.53,623251.17,1286586.77,0.0,1946781.49,1364191.18,0.00,727544.0,51.3,...,2668960,1,1999.0,15.0,1,0,0,0,1,0
4,2014.0,2018388.20,439001.78,1223160.02,0.0,1010201.52,1325444.21,0.00,761764.0,51.0,...,2184911,1,1997.0,17.0,0,0,1,0,1,0

In [86]:
# Fill NaN with 0
data_with_dummies = data_with_dummies.fillna(0)

In [87]:
# Create the y and X labels
y = data_with_dummies["won"]
X = data_with_dummies.drop(columns=['won'])
X.head()

,election,receipts,from_individuals,from_committees,from_candidate,disbursements,cash_on_hand,debts,total_pop,male_pop_percent,...,total_housing_units,spent,year,years_in_service,party_Democratic Party,party_Other,party_Republican Party,incumbent_challenger_open_Challenger,incumbent_challenger_open_Incumbent,incumbent_challenger_open_Open
0,2014.0,2643875.43,1137871.17,1443315.73,0.0,2543254.32,1143860.44,15607.71,727718.0,49.2,...,270685.0,4079869,2007.0,7.0,0,0,1,0,1,0
1,2014.0,2673006.24,1384157.24,1234898.00,0.0,3084464.90,1472329.77,0.00,726896.0,50.4,...,286382.0,3408251,2003.0,11.0,0,0,1,0,1,0
2,2014.0,1425973.57,567158.50,854339.38,0.0,1168222.75,858641.66,0.00,781134.0,48.6,...,330578.0,2735431,2008.0,6.0,0,0,1,0,1,0
3,2014.0,2522320.53,623251.17,1286586.77,0.0,1946781.49,1364191.18,0.00,727544.0,51.3,...,262554.0,2668960,1999.0,15.0,1,0,0,0,1,0
4,2014.0,2018388.20,439001.78,1223160.02,0.0,1010201.52,1325444.21,0.00,761764.0,51.0,...,290582.0,2184911,1997.0,17.0,0,0,1,0,1,0

In [88]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [89]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [90]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [91]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [92]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [93]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0          895           10
Actual 1            1          314

In [94]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.2659782207841157, 'year'),
 (0.16292678828136606, 'spent'),
 (0.15457721905903396, 'years_in_service'),
 (0.09252761130494828, 'incumbent_challenger_open_Incumbent'),
 (0.06534741005920038, 'from_committees'),
 (0.044842717806782284, 'cash_on_hand'),
 (0.04113979057106759, 'receipts'),
 (0.04101565292376897, 'from_individuals'),
 (0.02580674309446644, 'disbursements'),
 (0.02258427611963636, 'incumbent_challenger_open_Challenger'),
 (0.015643132209181673, 'from_candidate'),
 (0.006067620940027547, 'incumbent_challenger_open_Open'),
 (0.002929978712894613, 'asian_pop_percent'),
 (0.0026581750842169056, 'total_pop'),
 (0.002356088418420239, 'black_pop_percent'),
 (0.002254230148254138, 'election'),
 (0.0022145930429507453, 'hispanic_pop_percent'),
 (0.002069038811495679, 'white_pop_percent'),
 (0.002054256992992056, 'fortyfive_to_fiftyfour_percent'),
 (0.002023277601419026, 'ten_to_fourteen_percent'),
 (0.0019369446330589858, 'total_housing_units'),
 (0.0018675642975555756, 'sixtyfive_to_seventyfour_percent'),
 (0.0018132213377058312, 'twenty_to_twentyfour_percent'),
 (0.0017851366616190444, 'sixty_to_sixtyfour_percent'),
 (0.0017674332128744586, 'sixtyfive_and_over_percent'),
 (0.0017512642481261635, 'seventyfive_to_eightyfour_percent'),
 (0.001742239442508304, 'thirtyfive_to_fortyfour_percent'),
 (0.0016991108279895395, 'median_age'),
 (0.0016229107072385988, 'sixtyfive_and_over_female_percent'),
 (0.0016062784315982665, 'twentyfive_to_thirtyfour_percent'),
 (0.0016009748667937444, 'fiftyfive_to_fiftynine_percent'),
 (0.0015763211350439284, 'male_pop_percent'),
 (0.0015744100095222268, 'over_eightyfive_percent'),
 (0.001571376489214199, 'eighteen_and_over_percent'),
 (0.0015646442321118259, 'debts'),
 (0.0014633390219557882, 'sixtyfive_and_over_male_percent'),
 (0.001460036494178636, 'twentyone_and_over_percent'),
 (0.0014501455955578226, 'under_five_percent'),
 (0.0014426385650828807, 'sixtytwo_and_over_percent'),
 (0.0014299466903467627, 'female_pop_percent'),
 (0.001376058684230606, 'fifteen_nineteen_percent'),
 (0.0013428841710280519, 'eighteen_and_over_female_percent'),
 (0.0013021604018589677, 'eighteen_and_over_male_percent'),
 (0.0012647217702135983, 'five_to_nine_percent'),
 (0.0011748174817704422, 'american_indian_alaska_native_pop_percent'),
 (0.0009796793837123954, 'party_Republican Party'),
 (0.0008976407426827601, 'party_Democratic Party'),
 (0.0008116012441800012, 'other_race_pop_percent'),
 (0.0007848071531565897, 'native_hawaiian_pacific_islander_pop_percent'),
 (0.0003228701008453999, 'party_Other')]